{"metadata":{"modules":[{"name":"Fido2"}],"symbolKind":"case","role":"symbol","roleHeading":"Enumeration Case","title":"TGFErrorUserLockout","navigatorTitle":[{"kind":"identifier","text":"TGFErrorUserLockout"}],"fragments":[{"kind":"identifier","text":"TGFErrorUserLockout"}],"externalID":"c:@E@TGFError@TGFErrorUserLockout"},"sections":[],"abstract":[{"text":"The user is locked out of the authenticator due to too many failed attempts.","type":"text"}],"identifier":{"url":"doc:\/\/com.thalesgroup.oip.fido2\/documentation\/Fido2\/TGFError\/TGFErrorUserLockout","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/fido2\/tgferror\/tgferroruserlockout"]}],"hierarchy":{"paths":[["doc:\/\/com.thalesgroup.oip.fido2\/documentation\/Fido2","doc:\/\/com.thalesgroup.oip.fido2\/documentation\/Fido2\/TGFError"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"TGFErrorUserLockout","kind":"identifier"}]}]}],"kind":"symbol","references":{"doc://com.thalesgroup.oip.fido2/documentation/Fido2":{"title":"Fido2","url":"\/documentation\/fido2","abstract":[],"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/com.thalesgroup.oip.fido2\/documentation\/Fido2"},"doc://com.thalesgroup.oip.fido2/documentation/Fido2/TGFError":{"type":"topic","identifier":"doc:\/\/com.thalesgroup.oip.fido2\/documentation\/Fido2\/TGFError","title":"TGFError","abstract":[{"type":"text","text":"Represent different errors that might occur in Fido2 client operations."}],"kind":"symbol","url":"\/documentation\/fido2\/tgferror","role":"symbol","fragments":[{"text":"TGFError","kind":"identifier"}]},"doc://com.thalesgroup.oip.fido2/documentation/Fido2/TGFError/TGFErrorUserLockout":{"identifier":"doc:\/\/com.thalesgroup.oip.fido2\/documentation\/Fido2\/TGFError\/TGFErrorUserLockout","url":"\/documentation\/fido2\/tgferror\/tgferroruserlockout","role":"symbol","fragments":[{"text":"TGFErrorUserLockout","kind":"identifier"}],"type":"topic","abstract":[{"text":"The user is locked out of the authenticator due to too many failed attempts.","type":"text"}],"kind":"symbol","title":"TGFErrorUserLockout"}}}